/*
 * ToDo and Tracker
 * For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ToDoAndTracker);
  }
}(this, function(expect, ToDoAndTracker) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PetIdUploadImageBody', function() {
      beforeEach(function() {
        instance = new ToDoAndTracker.PetIdUploadImageBody();
      });

      it('should create an instance of PetIdUploadImageBody', function() {
        // TODO: update the code to test PetIdUploadImageBody
        expect(instance).to.be.a(ToDoAndTracker.PetIdUploadImageBody);
      });

      it('should have the property additionalMetadata (base name: "additionalMetadata")', function() {
        // TODO: update the code to test the property additionalMetadata
        expect(instance).to.have.property('additionalMetadata');
        // expect(instance.additionalMetadata).to.be(expectedValueLiteral);
      });

      it('should have the property file (base name: "file")', function() {
        // TODO: update the code to test the property file
        expect(instance).to.have.property('file');
        // expect(instance.file).to.be(expectedValueLiteral);
      });

    });
  });

}));
