/* 
 * ToDo and Tracker
 *
 * For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PetIdUploadImageBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PetIdUploadImageBodyTests
    {
        // TODO uncomment below to declare an instance variable for PetIdUploadImageBody
        //private PetIdUploadImageBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PetIdUploadImageBody
            //instance = new PetIdUploadImageBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PetIdUploadImageBody
        /// </summary>
        [Test]
        public void PetIdUploadImageBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PetIdUploadImageBody
            //Assert.IsInstanceOfType<PetIdUploadImageBody> (instance, "variable 'instance' is a PetIdUploadImageBody");
        }


        /// <summary>
        /// Test the property 'AdditionalMetadata'
        /// </summary>
        [Test]
        public void AdditionalMetadataTest()
        {
            // TODO unit test for the property 'AdditionalMetadata'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }

    }

}
