/* 
 * ToDo and Tracker
 *
 * For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Project
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProjectTests
    {
        // TODO uncomment below to declare an instance variable for Project
        //private Project instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Project
            //instance = new Project();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Project
        /// </summary>
        [Test]
        public void ProjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Project
            //Assert.IsInstanceOfType<Project> (instance, "variable 'instance' is a Project");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreateDate'
        /// </summary>
        [Test]
        public void CreateDateTest()
        {
            // TODO unit test for the property 'CreateDate'
        }
        /// <summary>
        /// Test the property 'DeadlineDate'
        /// </summary>
        [Test]
        public void DeadlineDateTest()
        {
            // TODO unit test for the property 'DeadlineDate'
        }
        /// <summary>
        /// Test the property 'ProjectNote'
        /// </summary>
        [Test]
        public void ProjectNoteTest()
        {
            // TODO unit test for the property 'ProjectNote'
        }
        /// <summary>
        /// Test the property 'Tasks'
        /// </summary>
        [Test]
        public void TasksTest()
        {
            // TODO unit test for the property 'Tasks'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'InvolvedUsers'
        /// </summary>
        [Test]
        public void InvolvedUsersTest()
        {
            // TODO unit test for the property 'InvolvedUsers'
        }
        /// <summary>
        /// Test the property 'IsArchieved'
        /// </summary>
        [Test]
        public void IsArchievedTest()
        {
            // TODO unit test for the property 'IsArchieved'
        }

    }

}
