/* 
 * ToDo and Tracker
 *
 * For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Task
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskTests
    {
        // TODO uncomment below to declare an instance variable for Task
        //private Task instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Task
            //instance = new Task();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Task
        /// </summary>
        [Test]
        public void TaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Task
            //Assert.IsInstanceOfType<Task> (instance, "variable 'instance' is a Task");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProjectIds'
        /// </summary>
        [Test]
        public void ProjectIdsTest()
        {
            // TODO unit test for the property 'ProjectIds'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'StepNum'
        /// </summary>
        [Test]
        public void StepNumTest()
        {
            // TODO unit test for the property 'StepNum'
        }
        /// <summary>
        /// Test the property 'ExpectedStartTime'
        /// </summary>
        [Test]
        public void ExpectedStartTimeTest()
        {
            // TODO unit test for the property 'ExpectedStartTime'
        }
        /// <summary>
        /// Test the property 'ExpectedFinishTime'
        /// </summary>
        [Test]
        public void ExpectedFinishTimeTest()
        {
            // TODO unit test for the property 'ExpectedFinishTime'
        }
        /// <summary>
        /// Test the property 'ExpectedTimeDuration'
        /// </summary>
        [Test]
        public void ExpectedTimeDurationTest()
        {
            // TODO unit test for the property 'ExpectedTimeDuration'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'RecurRule'
        /// </summary>
        [Test]
        public void RecurRuleTest()
        {
            // TODO unit test for the property 'RecurRule'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Test]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'AssignedUser'
        /// </summary>
        [Test]
        public void AssignedUserTest()
        {
            // TODO unit test for the property 'AssignedUser'
        }

    }

}
