/*
 * ToDo and Tracker
 * For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ToDoAndTracker);
  }
}(this, function(expect, ToDoAndTracker) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ToDoAndTracker.TaskApi();
  });

  describe('(package)', function() {
    describe('TaskApi', function() {
      describe('addTask', function() {
        it('should call addTask successfully', function(done) {
          // TODO: uncomment, update parameter values for addTask call and complete the assertions
          /*
          var opts = {};

          instance.addTask(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ToDoAndTracker.Task);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTask', function() {
        it('should call deleteTask successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTask call
          /*
          var opts = {};

          instance.deleteTask(tid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTaskById', function() {
        it('should call getTaskById successfully', function(done) {
          // TODO: uncomment, update parameter values for getTaskById call and complete the assertions
          /*
          var opts = {};

          instance.getTaskById(tid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ToDoAndTracker.Task);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTasks', function() {
        it('should call getTasks successfully', function(done) {
          // TODO: uncomment, update parameter values for getTasks call and complete the assertions
          /*
          var opts = {};

          instance.getTasks(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(ToDoAndTracker.Task);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateTask', function() {
        it('should call updateTask successfully', function(done) {
          // TODO: uncomment, update parameter values for updateTask call
          /*
          var opts = {};

          instance.updateTask(body, tid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
